version: '3'

volumes:
  mysql-data:
  composer-vendor:

services:
  mysqls:
    image: mysql:5.7
    env_file:
      - ./.devcontainer/services/mysqls/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.devcontainer/services/mysqls/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./.devcontainer/services/mysqls/logs:/var/log/mysql
    command: >
      bash -c "
        chmod 644 /etc/mysql/conf.d/*.cnf &&
        docker-entrypoint.sh mysqld
      "
    ports:
      - '${MYSQL_HOST_PORT:-3306}:3306'
  web-app:
    build:
      context: ./.devcontainer/dockerfiles/web-app
      args:
        TZ: 'Asia/Tokyo'
        PHP_MAJOR_VERSION: 8
        COMPOSER_VERSION: 2
    links:
      - mysqls
    restart: always
    env_file:
      - ./.devcontainer/services/web-app/.env
    volumes:
      - ./.devcontainer/services/web-app/env/laravel.env:${WORKING_DIR:-/src}/.env
      - ./.devcontainer/services/web-app/conf/httpd.conf:/etc/apache2/httpd.conf
      - ./.devcontainer/services/web-app/log/laravel:${WORKING_DIR:-/src}/storage/logs
      - ./.devcontainer/services/web-app/log/apache2:/var/log/apache2
      - ./src:${WORKING_DIR:-/src}
      # Laravel プロジェクトが src 直下でない場合、vendor ディレクトリのパスを調整する
      - composer-vendor:${WORKING_DIR:-/src}/vendor
    working_dir: ${WORKING_DIR:-/src}
    ports:
      - '${APACHE_HOST_PORT:-80}:80'
      - '${ARTISAN_SERVE_HOST_PORT:-8000}:8000'
